/**
 * Shared helpers for the operation engine.
 *
 * Every operation function is PURE: it deep-clones the spec, mutates the clone,
 * and returns it — the original is never touched (OPERATIONS.md §4.2). These
 * helpers centralise cloning, lookups, and the reserved-name logic that mirrors
 * `getReservedAuthResources` in lib/spec.ts.
 */

import type {
  GlobalAuthConfig,
  ResourceDefinition,
  ZeroAPISpec,
} from "@ludagg/zeroapi-runtime";
import { OperationError } from "./types";

/** Deep clone — operations mutate the clone, never the caller's object. */
export function clone<T>(value: T): T {
  return structuredClone(value);
}

/** Locate a resource by name or throw a clear OperationError. */
export function getResource(spec: ZeroAPISpec, name: string): ResourceDefinition {
  const r = spec.resources.find((res) => res.name === name);
  if (!r) {
    throw new OperationError(`Ressource introuvable : "${name}"`);
  }
  return r;
}

export function findResource(
  spec: ZeroAPISpec,
  name: string,
): ResourceDefinition | undefined {
  return spec.resources.find((res) => res.name === name);
}

/**
 * Resource names auto-generated by the runtime from the auth config. They are
 * forbidden as `resources[]` entries but valid as relation targets. Mirrors
 * `getReservedAuthResources` (lib/spec.ts:777) for the *current* spec state.
 */
export function getReservedResources(spec: ZeroAPISpec): Set<string> {
  const out = new Set<string>();
  const auth = spec.auth as GlobalAuthConfig | undefined;
  if (!auth) return out;
  const jwtEnabled = auth.jwt?.enabled === true || auth.strategy === "jwt";
  if (jwtEnabled) {
    out.add("User");
    out.add("RefreshToken");
  }
  if ((auth.oauth?.providers?.length ?? 0) > 0) {
    out.add("OAuthAccount");
  }
  return out;
}

export function isJwtEnabled(spec: ZeroAPISpec): boolean {
  const auth = spec.auth as GlobalAuthConfig | undefined;
  return auth?.jwt?.enabled === true || auth?.strategy === "jwt";
}

/** All resource names that can legally be a relation target. */
export function validRelationTargets(spec: ZeroAPISpec): Set<string> {
  const out = new Set(spec.resources.map((r) => r.name));
  for (const reserved of getReservedResources(spec)) out.add(reserved);
  return out;
}

export function requireNonEmpty(value: unknown, label: string): asserts value is string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new OperationError(`${label} est requis (chaîne non vide)`);
  }
}
