/**
 * Registry → Vercel AI SDK tools.
 *
 * `createOperationToolset(spec, …)` turns the 66 engine operations into a
 * `ToolSet` the LLM can call. The tool list is generated by walking the
 * registry's `OPERATION_DANGER` map (the source of truth for "which operations
 * exist") and joining each entry with its zod parameter schema + description
 * from `OPERATION_TOOLBOX`. Nothing here is hand-listed: add an operation to the
 * engine and a tool appears automatically (and the build fails until a schema
 * exists for it).
 *
 * When the model calls a tool, the tool runs `applyOperation` against the
 * toolset's CURRENT working spec and returns a compact ok/error result the model
 * can react to. The model never sees or writes the spec JSON — it only chooses
 * operations; the engine owns every mutation and the validity guarantee.
 *
 * Confirmation safety (OPERATIONS.md §4.2): the agent can NEVER confirm a
 * destructive operation itself. The `confirmed` flag is not part of any tool
 * schema; it is injected by the engine ONLY for operation types listed in
 * `approvedConfirmations` (i.e. a human already approved the impact). Any
 * unapproved destructive call comes back as `requiresConfirmation`, is recorded,
 * and the model is told to stop and surface the impact to the user.
 */

import { tool, type ToolSet } from "ai";
import type { ZeroAPISpec } from "@ludagg/zeroapi-runtime";
import { applyOperation } from "../operations";
import { OPERATION_DANGER } from "../operations/registry";
import type {
  ConfirmationImpact,
  Danger,
  Operation,
  OperationType,
} from "../operations/types";
import { OPERATION_TOOLBOX } from "./operation-schemas";

/** One entry in the agent's operation log (every emitted tool call). */
export interface AppliedOperationLog {
  type: OperationType;
  danger: Danger;
  params: Record<string, unknown>;
  outcome: "applied" | "rejected" | "needs-confirmation";
  error?: string;
}

export interface OperationToolset {
  /** The generated tools, keyed by operation type. */
  tools: ToolSet;
  /** Current working spec (reflects every applied operation). */
  getSpec(): ZeroAPISpec;
  /** Ordered log of every operation the model emitted. */
  getLog(): AppliedOperationLog[];
  /** Distinct impacts of destructive operations awaiting user confirmation. */
  getPendingConfirmations(): ConfirmationImpact[];
}

export interface ToolsetOptions {
  /**
   * Operation types the user has explicitly approved for this run. Only these
   * receive `confirmed: true`; everything else stays unconfirmed and bubbles up
   * as `requiresConfirmation`.
   */
  approvedConfirmations?: Iterable<OperationType>;
  /** Called for every emitted operation (success or failure) — used for logs. */
  onOperation?: (entry: AppliedOperationLog) => void;
}

/** Result object handed back to the LLM after each tool call. */
type ToolResult =
  | { ok: true; applied: OperationType; message: string }
  | { ok: false; error: string }
  | {
      ok: false;
      requiresConfirmation: true;
      impact: ConfirmationImpact;
      message: string;
    };

export function createOperationToolset(
  initialSpec: ZeroAPISpec,
  options: ToolsetOptions = {},
): OperationToolset {
  const approved = new Set<OperationType>(options.approvedConfirmations ?? []);
  const state = {
    spec: initialSpec,
    log: [] as AppliedOperationLog[],
    pending: [] as ConfirmationImpact[],
  };

  function record(entry: AppliedOperationLog): void {
    state.log.push(entry);
    options.onOperation?.(entry);
  }

  function execute(type: OperationType, params: Record<string, unknown>): ToolResult {
    // Build the engine operation. `confirmed` is injected ONLY when the user has
    // pre-approved this operation type — the model can never self-confirm.
    const op = { type, ...params } as Operation;
    if (approved.has(type)) {
      (op as { confirmed?: boolean }).confirmed = true;
    }

    let res;
    try {
      res = applyOperation(state.spec, op);
    } catch (e) {
      const error = e instanceof Error ? e.message : String(e);
      record({ type, danger: OPERATION_DANGER[type], params, outcome: "rejected", error });
      return { ok: false, error };
    }

    if (res.ok) {
      state.spec = res.spec;
      record({ type, danger: OPERATION_DANGER[type], params, outcome: "applied" });
      return { ok: true, applied: type, message: `Opération "${type}" appliquée.` };
    }

    if (res.requiresConfirmation) {
      const impact = res.requiresConfirmation;
      // De-dupe identical pending impacts (same op + reason).
      if (!state.pending.some((p) => p.operation === impact.operation && p.reason === impact.reason)) {
        state.pending.push(impact);
      }
      record({ type, danger: OPERATION_DANGER[type], params, outcome: "needs-confirmation", error: res.error });
      return {
        ok: false,
        requiresConfirmation: true,
        impact,
        message:
          `L'opération "${type}" est destructive et nécessite la confirmation de ` +
          `l'utilisateur. NE la confirme PAS toi-même. Arrête-toi et explique ` +
          `l'impact à l'utilisateur ; n'effectue pas d'autre changement lié tant ` +
          `qu'il n'a pas confirmé.`,
      };
    }

    record({ type, danger: OPERATION_DANGER[type], params, outcome: "rejected", error: res.error });
    return { ok: false, error: res.error };
  }

  // Generate one tool per registered operation — driven by the registry.
  const tools: ToolSet = {};
  for (const type of Object.keys(OPERATION_DANGER) as OperationType[]) {
    const meta = OPERATION_TOOLBOX[type];
    const danger = OPERATION_DANGER[type];
    tools[type] = tool({
      description: `[${danger}] ${meta.description}`,
      inputSchema: meta.schema,
      execute: async (input) => execute(type, (input ?? {}) as Record<string, unknown>),
    });
  }

  return {
    tools,
    getSpec: () => state.spec,
    getLog: () => state.log,
    getPendingConfirmations: () => state.pending,
  };
}
